"""changed customer status to bool

Revision ID: 2a589b90409d
Revises: 296e31d1eb72
Create Date: 2025-02-22 13:59:54.762873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a589b90409d'
down_revision: Union[str, None] = '296e31d1eb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index('ix_customers_customer_status', table_name='customers')
    op.drop_column('customers', 'customer_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('customer_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_customers_customer_status', 'customers', ['customer_status'], unique=False)
    op.drop_column('customers', 'is_active')
    # ### end Alembic commands ###
