"""stuff

Revision ID: d0b50deb01f2
Revises: 
Create Date: 2025-02-22 13:14:27.597566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b50deb01f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=False),
    sa.Column('customer_street', sa.String(), nullable=False),
    sa.Column('customer_city', sa.String(), nullable=False),
    sa.Column('customer_state', sa.String(), nullable=False),
    sa.Column('customer_postal', sa.String(), nullable=False),
    sa.Column('customer_website', sa.String(), nullable=True),
    sa.Column('customer_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_name'), 'customers', ['customer_name'], unique=False)
    op.create_index(op.f('ix_customers_customer_phone'), 'customers', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_customers_customer_status'), 'customers', ['customer_status'], unique=False)
    op.create_index(op.f('ix_customers_customer_website'), 'customers', ['customer_website'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_first_name', sa.String(), nullable=False),
    sa.Column('lead_last_name', sa.String(), nullable=False),
    sa.Column('lead_email', sa.String(), nullable=False),
    sa.Column('lead_phone', sa.String(), nullable=False),
    sa.Column('lead_message', sa.String(), nullable=True),
    sa.Column('lead_company', sa.String(), nullable=False),
    sa.Column('lead_website', sa.String(), nullable=True),
    sa.Column('lead_status', sa.String(), nullable=True),
    sa.Column('lead_converted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_lead_company'), 'leads', ['lead_company'], unique=False)
    op.create_index(op.f('ix_leads_lead_email'), 'leads', ['lead_email'], unique=False)
    op.create_index(op.f('ix_leads_lead_first_name'), 'leads', ['lead_first_name'], unique=False)
    op.create_index(op.f('ix_leads_lead_last_name'), 'leads', ['lead_last_name'], unique=False)
    op.create_index(op.f('ix_leads_lead_phone'), 'leads', ['lead_phone'], unique=False)
    op.create_index(op.f('ix_leads_lead_status'), 'leads', ['lead_status'], unique=False)
    op.create_index(op.f('ix_leads_lead_website'), 'leads', ['lead_website'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_first_name', sa.String(), nullable=False),
    sa.Column('contact_last_name', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_contact_email'), 'contacts', ['contact_email'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_contact_email'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_leads_lead_website'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_last_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_first_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_company'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_website'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
